### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/latin-ecclesiastic-accents#1]
Thanks for starting work on this.
Any reason why the file doesn't match the README and doesn't use æ and œ but ae and oe?
I guess it would be easiest to just mass replace all ae with æ, áe and aé with ǽ, oe with œ, perhaps also capital letters, and then figure out how to represent oé or óe - œ with accent, where unicode doesn't have such char - I usually just use combining ' character together with œ.
I've used your file to check all the *.gabc files I have around, and ended up with a list of right now 857 words that I need to still double check (where possible verify against Solesmes books, otherwise google search them, ...), but many of them are simply missing in the list, in other cases it will be my typoes and in other cases I'll need to verify where the accent should be).  Once I get the list cleaned up, I'll post it here (will try to split the list into words verified by Solesmes and others.

**Comment by eroux** [comment]
Hmm, in fact there is really a lot of discussions on this right now, it's really not stable enough to have any reliable result yet, especially for hymns. For prose, you can take a look at branch 10.3 of [collatinus](https://github.com/biblissima/collatinus-src) (note that you also need [collatinus-data](https://github.com/biblissima/collatinus-data) to make it work). Even that is still quite experimental... Things start to stabilize a bit, but there are still many grey areas. I hope to have at least some proper documentation by the end of the month...

**Comment by jakubjelinek** [comment]
Still working on my list and still to try collatinus.
Anyway, I also found
https://github.com/DivinumOfficium/divinum-officium/blob/master/admin/accent_table
as another source of latin accents, while it has just 13k words, it contains lots of words commonly used in the office.

**Comment by jakubjelinek** [comment]
Out of the 13k words, most of them are also in the verbs.txt here, but 4745 words are not.
Out of these 4745, 242 are in verbs.txt with different accents from the accent_table (I've performed
sed 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZáéíóúýǽ/abcdefghijklmnopqrstuvwxyzaeiouyæ/'
for the comparison, so some known correct differences like:
María
vs.
mária
are in that list too, but supposedly this is a list of words that certainly need double checking, then there are some (though not many) one and two syllable words in those 4745, and the rest could be hopefully added.

**Comment by eroux** [comment]
I have a list of words as accented in the psalms, proofread by Solesmes so quite reliable. The main problem being that while the way to accentuate prose is relatively simple, there are a lot of blur areas in the way to accentuate hymns, and the determination of diphtongues in hymns make it even more difficult, so we're planning to make a repository of accented hymns, with the same accents as in the Vatican editions, this seems to be the only way to have correctly accented hymns, and also to be able to study the way they are accentuated.

To take an example for hymns: in prose, the rules make words accentuated as: 
muliérem, filiólus, intégrum, tonítrus and ténebræ, while in hymns, it's common to find them as mulíerem, filíolus, íntegrum et tónitrus and tenébræ. The rules guiding these accents are not clear...

**Comment by jakubjelinek** [comment]
Also, I found verbs.txt in this repo to contain lots of duplicates (111640 words).
So for psalms, antiphons and prose, could we perhaps have multiple word lists depending on reliability, have smaller ones with higher reliability and fallback on larger ones with lower one?
What sort order shall we use in those files?  LC_ALL=en_US.UTF-8, LC_ALL=C.UTF-8, something different (I doubt there are collation rules for latin)?  Would it be useful to submit patches to remove redundancies from verbs.txt (depends on the sorting choice), change ae to æ, áe and aé to ǽ, oe to œ and proofread those changes (to leave in Israel, Michael etc.)?
My interest is both prose (Matins readings mostly), antiphons, psalms and hymns.

**Comment by eroux** [comment]
I don't think there's any point in improving verbs.txt, it's only here because I didn't have time to remove it. This repository will contain only some documentation and pointers, and maybe a hymn corpus. The accentuation itself will be in Collatinus only, try the 10.3 branch for something that is more or less working. Having a full list of words plus a list of all ambiguities and informations on these ambiguities will be too much (around 1 million entries), it seems taking the road of lemmatization and analysis is a safer way, and the data is already in Collatinus, so I don't see any point in the constitution of such a list. If you really want to get a list (which might be useful), I think it's best to discuss the format further beforehand... 

Do you really prefer a list over Collatinus? We're discussing the structure of Collatinus these days, we'll isolate the lemmatization, desinences, etc. into a library that will be usable from C.

For the hymns, noone knows the rules (even in Solesmes), so the only way is to constitute a corpus. We're planning to OCRize a very big accented hymnarium from Vatican editions, in the meantime there is http://www.almudi.org/Portals/0/docs/Breviario/fuentes/breviario.asp?tiempo=1 for that, the accents should be reliable, but accents are lacking on æ and œ on the website (the problem does not appear in their ebook format).

**Comment by eroux** [comment]
About collation, it would be interesting to provide some rules for Latin including accents and usual vowel length marks, they should be quite easy to write... It's easily testable from Python, see https://github.com/eroux/tibetan-collation for an example

**Comment by eroux** [comment]
(closing as the discussion continued through email)
