### ISSUE TITLE
Documentation: compound words

### ISSUE THREAD

**Issue by wehro** [gregorio-project/latin-ecclesiastic-accents#11]
The documention should make more clear how compound words of type *haru-spex* and *ante-sto* have to be accented. The paenultimate contains a short vowel here and it is not quite clear if it has to be considered as long, as the following two consonants belong to the second part of the compound.

**Comment by BrRoman** [comment]
Dear wehro,

Thanks for your feedback!

Your idea is interesting, but for now I would suggest to accent with a long penultimate (i.e. to stand at the existing rules). The dictionaries, indeed, don't give any length for the penultimate of the compounds, and for the moment I can't remember any liturgical text using these words where we could verify how they were accented.

Collatinus give harúspex and antésto, but it doesn't really close the question, since Collatinus automatically puts a long before two consonants whenever no length is given by the dictionaries.

The next step to move forward and validate your suggestion would be to find other words of the same type, with a short penultimate followed by two consonantics, and accented in the liturgical books. Then we could conclude.

Yours in Christ.
Br. Roman Mary

**Comment by wehro** [comment]
Unfortunately, these words are rare.
Besides *haru-spex* and *ante-sto*, I found *vesti-spex*, *exti-spex*, *anti-sto* (variant of *ante-sto*), and *anti-stes*. The latter is used for “bishop” in Christian texts, but I don't know if it occurs in any accented liturgical text.

**Comment by BrRoman** [comment]
"Antistes" is a good lead, but for the moment I've found it only in the form "antístit*". I'll keep searching. Thanks a lot!

Yours in Christ.
Br. Roman Mary

**Comment by BrRoman** [comment]
A quick research in the resource files of [Divinum Officium](http://divinumofficium.com) gives 3 times the result _antístes_. So I think this is the ecclesiastic accentuation rule: even a native short penultimate becomes long before two consonants.
Do you think it has to be added to our rules? Is it a good formulation?

Yours in Christ.
Br. Roman Mary

**Comment by wehro** [comment]
Thank you for your research.
I propose to add one or two examples of the *antistes* type to rule 3 for “Determining the quantity of a syllable”.

**Comment by BrRoman** [comment]
I've pushed a modif. Please tell me whether it that suits you.

Merry and holy Christmas.
Br. Roman Mary

**Comment by wehro** [comment]
The examples are good.
My sources give some different vowel lengths (*hărŭ-spĕx*, *ăntĕ-stō*, *ăntĭ-stĕs*), but that does not matter here.

**Comment by BrRoman** [comment]
I have corrected. Thanks a lot, and sorry for having closed the issue prematurely.

Yours in Christ.
Br. Roman Mary
